# SVN revision: $Rev: $
# Date of last change: $LastChangedDate: 24/02/2012 $
# Last changed by: $LastChangedBy: ccampbell $
# 
# Original author: fgochez
# Copyright Mango Solutions, Chippenham, UK
###############################################################################


#' Calculate Maximum Concentration and time of maximum concentration
#'
#' Finds the maximum concentration value and the first time point 
#' (in the sense of corresponding to the minimal index)
#' with that concentration.
#'
#' @title Calculate Maximum Concentration and time of maximum concentration
#' @param Conc numeric vector of concentrations
#' @param Time numeric vector of time points (parallel to \code{Conc})
#' @return list with numeric scalar (length 1 vector) components "cmax", "tmax" and "index". See notes for further processing.
#' @export
#' @note The following error checks / processing will be performed:
#'  \enumerate{
#'      \item If \code{Conc} or \code{Time} are of length 0, NA is returned for both values
#'      \item If the sum of \code{Code} (after omitting missing values) is 0, NA is returned for both values
#'      \item If \code{cmax} is 0, NA is returned for \code{tmax}
#'      \item \code{cmax} is computed by stripping NA values from \code{Conc}
#'      \item if \code{Conc} and \code{Time} are not equal length numeric vectors, an exception will be generated by
#'            \code{\link{checkNumericSameLength}}
#'  }
#' @examples
#' Theoph.2 <- subset(Theoph, Subject == 2)
#' CmaxTmax( Theoph.2$conc, Theoph.2$Time ) 
#' @keywords math

CmaxTmax <- function(Conc, Time) {
   
    checkNumericSameLength(Time, Conc, "Time", "Concentration")
        
    # timeConc : data.frame which holds time and concentration in a single object
    
    timeConc <- data.frame(Time, Conc)
    
    # Initialize variables, set default value to NA
    # cmax : single element numeric vector, will hold maximum concentration
    # tmax : single element numeric vector, will hold first time of maximum concentration
    # index : single element numeric vector, will hold index of maximum concentration
    
    cmax <- NA
    tmax <- NA
    index <- NA
    
    ## Do Data check : there should be at least one conc/time element, and sum of concentrations should be non-zero
    
    if(nrow(timeConc) < 1){
        return(list(cmax = cmax, tmax = tmax, index = index))
    }
    if(sum(timeConc$Conc, na.rm=TRUE) == 0){
        return(list(cmax = cmax, tmax = tmax, index = index))
    }
    
    # Find the maximum concentration value (ignore NA values).
    
    cmax <- max(timeConc$Conc, na.rm = TRUE)
    
    # Get the indexes that match cm and then find the minimum index value.
    # This assumes that x is sorted in assending order of time to get the first occurance of cm.
    
    index <- min(which(timeConc$Conc == cmax))
    tmax <- timeConc[index, "Time"]
    
    # cmax should be greater than 0, else tmax is NA
    
    if( cmax == 0 ){ 
        tmax <- NA 
    }
    
    return(list(cmax = cmax, tmax = tmax, index = index))
}
