# SVN revision: $Rev: $
# Date of last change: $LastChangedDate: 24/02/2012 $
# Last changed by: $LastChangedBy: ccampbell $
# 
# Original author: fgochez
# Copyright Mango Solutions, Chippenham, UK
###############################################################################


#' Calculate Maximum concentration and time of maximum concentration
#'
#' Finds the maximum concentration value and the first time point 
#' (in the sense of corresponding to the minimal index)
#' with that concentration.
#'
#' @title Calculate Maximum concentration and time of maximum concentration
#' @param conc numeric vector of concentrations
#' @param time numeric vector of time points (parallel to \code{conc})
#' @return list with numeric scalar (length 1 vector) components "cmax", "tmax" and "index". See notes for further processing.
#' @export
#' @note The following error checks / processing will be performed:
#'  \enumerate{
#'      \item If \code{conc} or \code{time} are of length 0, NA is returned for both values
#'      \item If the sum of \code{Code} (after omitting missing values) is 0, NA is returned for both values
#'      \item If \code{cmax} is 0, NA is returned for \code{tmax}
#'      \item \code{cmax} is computed by stripping NA values from \code{conc}
#'      \item if \code{conc} and \code{time} are not equal length numeric vectors, an exception will be generated by
#'            \code{checkNumericSameLength}
#'  }
#' @examples
#' Theoph.2 <- subset(Theoph, Subject == 2)
#' CmaxTmax( Theoph.2$conc, Theoph.2$time ) 
#' @keywords math

CmaxTmax <- function(conc, time) {
   
    checkNumericSameLength(time, conc, "time", "concentration")
        
    # timeconc : data.frame which holds time and concentration in a single object
    
    timeconc <- data.frame(time, conc)
    
    # Initialize variables, set default value to NA
    # cmax : single element numeric vector, will hold maximum concentration
    # tmax : single element numeric vector, will hold first time of maximum concentration
    # index : single element numeric vector, will hold index of maximum concentration
    
    cmax <- NA
    tmax <- NA
    index <- NA
    
    ## Do Data check : there should be at least one conc/time element, and sum of concentrations should be non-zero
    
    if(nrow(timeconc) < 1){
        return(list(cmax = cmax, tmax = tmax, index = index))
    }
    if(sum(timeconc$conc, na.rm=TRUE) == 0){
        return(list(cmax = cmax, tmax = tmax, index = index))
    }
    
    # Find the maximum concentration value (ignore NA values).
    
    cmax <- max(timeconc$conc, na.rm = TRUE)
    
    # Get the indexes that match cm and then find the minimum index value.
    # This assumes that x is sorted in assending order of time to get the first occurance of cm.
    
    index <- min(which(timeconc$conc == cmax))
    tmax <- timeconc[index, "time"]
    
    # cmax should be greater than 0, else tmax is NA
    
    if( cmax == 0 ){ 
        tmax <- NA 
    }
    
    return(list(cmax = cmax, tmax = tmax, index = index))
}
